Free sports realted APIs
TheLearneer/api-party pull request #214
Opened 2022-10-02 06:15 UTC by abhijeet007rocks8

APIs added are -:
- [Free NBA](https://www.balldontlie.io/#introduction)
- [API Football](https://www.api-football.com/documentation-v3)

2022-10-03 03:50 UTC, TheLearneer requested changes
Thank you @abhijeet007rocks8 for your contributions.
For the PR to be accepted, please go through the requested change.

2022-10-03 03:50 UTC, TheLearneer commented on src/content/apis/sports/api-football.md
> +logo: https://www.api-football.com/public/img/home1/hero-banner.png
The logo has to be downloaded and place inside the repository itself.
Please check the contributing guides for more details.

2022-10-03 03:50 UTC, TheLearneer commented on src/content/apis/sports/free-nba.md
> +logo: https://www.balldontlie.io/images/cryingjordan.jpeg
The logo has to be downloaded and place inside the repository itself.
Please check the contributing guides for more details.

2022-10-03 07:14 UTC, abhijeet007rocks8 commented
@TheLearneer Requested Changes have been made

2022-10-04 15:18 UTC, TheLearneer requested changes

2022-10-04 15:18 UTC, TheLearneer commented on src/content/apis/sports/api-football.md
> +logo: API_Football.png
```suggestion
logo: API-Football.png

```

2022-10-04 15:24 UTC, abhijeet007rocks8 commented
@TheLearneer Logo Name is fixed

2022-10-04 15:28 UTC, merged