Chores/movie quotes generator
TheLearneer/api-party pull request #239
Opened 2022-10-07 09:14 UTC by dibashthapa

2022-10-07 12:11 UTC, TheLearneer requested changes
Please remove the changes that are not related to this PR

2022-10-07 12:20 UTC, dibashthapa commented
> Please remove the changes that are not related to this PR

Done @TheLearneer

2022-10-07 14:03 UTC, TheLearneer requested changes
Please go through the requested changes 🙇

2022-10-07 17:00 UTC, dibashthapa commented
@TheLearneer Made changes accordingly

2022-10-08 01:08 UTC, TheLearneer commented on src/content/apis/entertainment/movie-quotes.md
> +
```suggestion
```

2022-10-08 04:59 UTC, dibashthapa commented on src/content/apis/entertainment/movie-quotes.md
> +
Done @TheLearneer

2022-10-08 13:16 UTC, TheLearneer approved these changes
LGTM, thank you for your contribution @dibashthapa

2022-10-08 13:17 UTC, merged