feat: Vonage API
TheLearneer/api-party pull request #246
Opened 2022-10-10 17:32 UTC by rahmat-st

2022-10-11 08:53 UTC, TheLearneer reviewed
The Vonage API seems to not have any free plan (not talking about demos).
As of now, this API list contains only the APIs that have free plans.

@rahmat-st can you please confirm it the API has only paid plans?

2022-10-11 09:40 UTC, rahmat-st commented
Do you mean the demo version is like a few days trial period?

I think Vonage is similar to Stripe. Vonage provides a free version for the sandbox/testing environment. If Stripe charges a fee for each transaction, Vonage is the same, you will pay according to the service you use in production.

https://www.vonage.com/communications-apis/pricing/

2022-10-11 09:42 UTC, TheLearneer commented
That makes sense @rahmat-st 

However please make sure to comply with all the requirement mentioned in #2 for the PR to be accepted as part of Hacktoberfest 🙏

2022-10-11 09:47 UTC, rahmat-st commented
No problem, I already have 4 or more PRs for hacktoberfest btw

2022-10-28 07:31 UTC, TheLearneer approved these changes

2022-10-29 06:20 UTC, TheLearneer requested changes
@rahmat-st Please make this change and we can proceed with merging this PR 🙏

2022-10-29 06:20 UTC, TheLearneer commented on src/content/apis/development/vonage.md
> +  https: true
```suggestion
  https: true
  pricing: paid
```

2022-11-03 09:40 UTC, closed without merging