added Twilio Lookup API
TheLearneer/api-party pull request #323
Opened 2022-10-31 10:40 UTC by namanjoshi19

Returns phone number information matching the specified request. Formatting information is standard. Carrier, Caller Name, and phone number type information can be requested, in addition to using Add-ons to access 3rd party data sources.

2022-10-31 10:45 UTC, TheLearneer requested changes

2022-10-31 10:45 UTC, TheLearneer commented on src/content/apis/SMS/TWILIO LOOKUP
> + -
Please add the appropriate category. For this case it should be `development`

2022-10-31 10:45 UTC, TheLearneer commented on src/content/apis/SMS/TWILIO LOOKUP
> +  pricing: free
```suggestion
  pricing: upgradable
```

2022-10-31 10:45 UTC, TheLearneer commented on src/content/apis/SMS/TWILIO LOOKUP
> +url: https://rapidapi.com/twilio/api/twilio-lookup/
Twilio has their own documentation page, please add the link to it 🙏

2022-10-31 10:45 UTC, TheLearneer commented on src/content/apis/SMS/TWILIO LOOKUP
> +logo:
Please add the logo of Twilio 🙏

2022-10-31 12:02 UTC, TheLearneer requested changes
@namanjoshi19 The file format is completely incorrect, please check [CONTRIBUTING.md](https://github.com/TheLearneer/api-party/blob/main/CONTRIBUTING.md) and make the changes accordingly

2022-10-31 12:11 UTC, namanjoshi19 commented
can i add the logo directly to the file ?

2022-11-03 09:39 UTC, TheLearneer reviewed
The file doesn't follow the contributing guidelines 🙏

2022-11-03 09:39 UTC, closed without merging